/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetfime;;




import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author hp
 */
public class Beneficiaire extends javax.swing.JFrame {
Connection conn;
PreparedStatement ps;
Statement st;
ResultSet rs;
static String test;
//private int numeroFidele;




    /**
     * Creates new form Fidele
     */
    
    
    public Beneficiaire(){
        initComponents();
        
        //modifier le titre du formulaire
        this.setTitle("Beneficiaire");
        //centrer le formulaire
        this.setLocationRelativeTo(null);
        //ne pas permettre le redimensionnement du formulaire
        this.setResizable(false);   
        this.setIconImage(new ImageIcon(getClass().getResource("pentecote.png")).getImage());
        conn = ConexionBD.Conexion();
    }
    
     
    public void cleardonnee() {    
        mat.setText("");
        nombenf.setText("");
        prenombenf.setText("");
        combosexe.setSelectedIndex(-1);
        datenaiss.setDate(null);
        professionbenf.setText("");
        contactbenf.setText("");
        quartierbenf.setText("");
        comboparent.setSelectedIndex(-1);
    }

    public void afficherBeneficiaire(){
        try {
            String requete = "select numBen,matricule,nomBen,prenomBen,dateNaissance,sexe,contact,quartier,profession,numMembre from membre";
            ps = conn.prepareStatement(requete);
            rs = ps.executeQuery();
            tablebeneficiaire.setModel(DbUtils.resultSetToTableModel(rs));
          }  catch (SQLException e) {
           JOptionPane.showMessageDialog(null, "erreur BD");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ajouterbenf = new javax.swing.JButton();
        prenombenf = new javax.swing.JTextField();
        mat = new javax.swing.JTextField();
        nombenf = new javax.swing.JTextField();
        quartierbenf = new javax.swing.JTextField();
        professionbenf = new javax.swing.JTextField();
        modif = new javax.swing.JButton();
        searchMembre = new javax.swing.JButton();
        matrech = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        datenaiss = new com.toedter.calendar.JDateChooser();
        combosexe = new javax.swing.JComboBox();
        actualiser = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        accueil = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablebeneficiaire = new javax.swing.JTable();
        afficherbenef = new javax.swing.JButton();
        imprimfideledime = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        contactbenf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        comboparent = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enregistrement des bénéficiaires", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), java.awt.Color.blue)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setText("Matricule");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel3.setText("Nom");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel5.setText("Prénoms");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel12.setText("Quartier");

        ajouterbenf.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ajouterbenf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Button-Add-icon.png"))); // NOI18N
        ajouterbenf.setText("Ajouter");
        ajouterbenf.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ajouterbenf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterbenfActionPerformed(evt);
            }
        });

        prenombenf.setBackground(new java.awt.Color(204, 255, 204));
        prenombenf.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        prenombenf.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        mat.setBackground(new java.awt.Color(204, 255, 204));
        mat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        mat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        nombenf.setBackground(new java.awt.Color(204, 255, 204));
        nombenf.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        nombenf.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        quartierbenf.setBackground(new java.awt.Color(204, 255, 204));
        quartierbenf.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        quartierbenf.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        professionbenf.setBackground(new java.awt.Color(204, 255, 204));
        professionbenf.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        professionbenf.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        modif.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        modif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update icon.png"))); // NOI18N
        modif.setText("Modifier");
        modif.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifActionPerformed(evt);
            }
        });

        searchMembre.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        searchMembre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        searchMembre.setText("Recherche par le matricule");
        searchMembre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchMembre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchMembreActionPerformed(evt);
            }
        });

        matrech.setBackground(new java.awt.Color(204, 255, 204));
        matrech.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        matrech.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        matrech.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                matrechKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel7.setText("Sexe");

        datenaiss.setBackground(new java.awt.Color(204, 255, 204));
        datenaiss.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        datenaiss.setForeground(new java.awt.Color(204, 255, 204));
        datenaiss.setDateFormatString("yyyy-MM-dd");
        datenaiss.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        datenaiss.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                datenaissComponentAdded(evt);
            }
        });
        datenaiss.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                datenaissAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        datenaiss.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                datenaissMouseReleased(evt);
            }
        });
        datenaiss.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                datenaissKeyReleased(evt);
            }
        });

        combosexe.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        combosexe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculin", "Feminin" }));
        combosexe.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        actualiser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/actualiser.jpg"))); // NOI18N
        actualiser.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        actualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualiserActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel6.setText("Profession");

        accueil.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        accueil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/accueil1.png"))); // NOI18N
        accueil.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        accueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accueilActionPerformed(evt);
            }
        });

        tablebeneficiaire.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 185, 244)));
        tablebeneficiaire.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tablebeneficiaire.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° bénéficiare", "Matricule", "Nom", "Prénoms", "Sexe", "Date Naissance", "Profession", "Contact", "Quartier", "Nom parent"
            }
        ));
        tablebeneficiaire.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablebeneficiaireMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablebeneficiaire);

        afficherbenef.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        afficherbenef.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icone affichage1.jpg"))); // NOI18N
        afficherbenef.setText("Afficher");
        afficherbenef.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        afficherbenef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afficherbenefActionPerformed(evt);
            }
        });

        imprimfideledime.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        imprimfideledime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/printer.png"))); // NOI18N
        imprimfideledime.setText("Rapport");
        imprimfideledime.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        imprimfideledime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimfideledimeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setText("Date naissance");

        contactbenf.setBackground(new java.awt.Color(204, 255, 204));
        contactbenf.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        contactbenf.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel8.setText("Nom parent");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel9.setText("Contact");

        comboparent.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        comboparent.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(ajouterbenf, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(modif, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(afficherbenef, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addComponent(imprimfideledime, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(actualiser, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(accueil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchMembre, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(matrech, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombenf, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prenombenf, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datenaiss, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combosexe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(professionbenf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboparent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quartierbenf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactbenf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 948, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(accueil, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actualiser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchMembre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(matrech, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(combosexe, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactbenf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nombenf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel1))
                    .addComponent(datenaiss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(quartierbenf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prenombenf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(professionbenf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(comboparent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ajouterbenf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modif, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(afficherbenef, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imprimfideledime, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 956, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void ajouterbenfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterbenfActionPerformed
    
        String reqins = "insert into beneficiaire (matricule,nomBen,prenomBen,sexe,dateNaissance,"
                      + "profession,contact,quartier,numMembre) values(?,?,?,?,?,?,?,?,?)";
        try{  
            ps = conn.prepareStatement(reqins);
            ps.setString(1, mat.getText());
            ps.setString(2, nombenf.getText());
            ps.setString(3, prenombenf.getText());
            ps.setString(4, (String) combosexe.getSelectedItem());
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
            String date = sdf.format(datenaiss.getDate());
            ps.setString(5, date);
            ps.setString(6, professionbenf.getText());
            ps.setString(7, contactbenf.getText()); 
            ps.setString(8, quartierbenf.getText());
            ps.setString(9, (String) comboparent.getSelectedItem());      
            ps.executeUpdate();
//          JOptionPane.showMessageDialog(this,"Insertion réussie!!!");
            mat.setText("");
            nombenf.setText("");
            prenombenf.setText("");
            combosexe.setSelectedIndex(-1);
            datenaiss.setDate(null);
            professionbenf.setText("");
            contactbenf.setText("");
            quartierbenf.setText("");
            comboparent.setSelectedIndex(-1);
            afficherBeneficiaire();
            } catch (SQLException ex) {
//            Logger.getLogger(Fidele.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showInputDialog(null, "Cet matricule existe dejà, Veuillez changer de matricule!"+ex.getMessage());
        } 
    }//GEN-LAST:event_ajouterbenfActionPerformed

    private void modifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifActionPerformed
        
        DefaultTableModel d1 = (DefaultTableModel)tablebeneficiaire.getModel();
        int selectIndex = tablebeneficiaire.getSelectedRow();

        int numBen = Integer.parseInt(d1.getValueAt(selectIndex, 0).toString());
        String matricule = mat.getText();
        String nomBen  = nombenf.getText();
        String prenomBen = prenombenf.getText();
        String sexe = (String) combosexe.getSelectedItem();
        String dateNaissance = ((JTextField) datenaiss.getDateEditor().getUiComponent()).getText();
        String profession = professionbenf.getText();
        String contact = contactbenf.getText();
        String quartier = quartierbenf.getText();
        int numMembre = Integer.parseInt(d1.getValueAt(selectIndex, 0).toString());
        try {    
        ps = conn.prepareStatement("update beneficiaire set matricule=?,nomBen=?,prenomBen=?,sexe=?,"
                                 + "dateNaissance=?,profession=?,contact=?,quartier=?,numMembre=? where numBen=?");
//        matricule,nomBen,prenomBen,sexe,dateNaissance,profession,contact,quartier,numMembre
        ps.setString(1, matricule);
        ps.setString(2, nomBen);
        ps.setString(3, prenomBen);
        ps.setString(4, sexe);
        ps.setString(5, dateNaissance);
        ps.setString(6, profession);
        ps.setString(7,contact);
        ps.setString(8,quartier); 
         ps.setInt(9, numMembre);
        ps.setInt(10, numBen);
        ps.executeUpdate();
//      JOptionPane.showMessageDialog(null,"Mise à jour effectuée!");
            afficherBeneficiaire();        
            mat.setText("");
            nombenf.setText("");
            prenombenf.setText("");
            combosexe.setSelectedIndex(-1);
            datenaiss.setDate(null);
            professionbenf.setText("");
            contactbenf.setText("");
            quartierbenf.setText("");
            comboparent.setSelectedIndex(-1);
          
            mat.requestFocus();
        } 
        catch (SQLException ex) {
            Logger.getLogger(Beneficiaire.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_modifActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
  
    }//GEN-LAST:event_formWindowOpened

    private void searchMembreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchMembreActionPerformed

        DefaultTableModel model = (DefaultTableModel) tablebeneficiaire.getModel();
                 model.setRowCount(0); // vider le tableau
                try{
                        st= (Statement) conn.createStatement();
                        String req="select * from beneficiaire where matricule='"+matrech.getText()+"'";
                        rs=st.executeQuery(req);
            //          while(rs.next()){
                           if (rs.next()) {
                             Object [] fide={rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),
                             rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10)};
                                  model.addRow(fide);
                              }else{
                                JOptionPane.showMessageDialog(null, "Vérifier votre saisie !");
                            }
                          tablebeneficiaire.setModel(model);
                           matrech.setText("");
                        }
                    catch(SQLException se){
                            JOptionPane.showMessageDialog(this, se.getMessage());
                        }
  
    }//GEN-LAST:event_searchMembreActionPerformed

    private void datenaissComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_datenaissComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_datenaissComponentAdded

    private void datenaissAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_datenaissAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_datenaissAncestorAdded

    private void datenaissMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datenaissMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_datenaissMouseReleased

    private void datenaissKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_datenaissKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_datenaissKeyReleased

    private void actualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualiserActionPerformed
        // TODO add your handling code here:
        Beneficiaire benf = new Beneficiaire();
        benf.setVisible(true);
        dispose();
    }//GEN-LAST:event_actualiserActionPerformed

    private void accueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accueilActionPerformed
        // TODO add your handling code here:
        Accueil acc = new Accueil();
        acc.setVisible(true);
        dispose();
    }//GEN-LAST:event_accueilActionPerformed

    private void tablebeneficiaireMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablebeneficiaireMouseClicked
         
         try{
            int row = tablebeneficiaire.getSelectedRow();
            this.test = (tablebeneficiaire.getModel().getValueAt(row, 0).toString());
            String req = " select * from  beneficiaire where numBen = '" + test + "' ";
            ps = conn.prepareStatement(req);
            rs = ps.executeQuery();
           if (rs.next()) {
            mat.setText(rs.getString("matricule"));
            nombenf.setText(rs.getString("nomBen"));
            prenombenf.setText(rs.getString("prenomBen"));
            combosexe.setSelectedItem(rs.getString("sexe"));
            datenaiss.setDate(rs.getDate("datenaissance"));
            professionbenf.setText(rs.getString("contact")); 
            contactbenf.setText(rs.getString("contact"));
            quartierbenf.setText(rs.getString("profession"));
            comboparent.setSelectedItem(rs.getString("numMembre"));
          
            }  
        } catch(Exception ex){
            
       }
            
    }//GEN-LAST:event_tablebeneficiaireMouseClicked

    private void afficherbenefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afficherbenefActionPerformed
        // TODO add your handling code here:
      afficherBeneficiaire();
    }//GEN-LAST:event_afficherbenefActionPerformed

    private void imprimfideledimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimfideledimeActionPerformed
        try {
            // TODO add your handling code here:
            JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\Kluce\\Documents\\NetBeansProjects\\Gestiondime\\src\\report\\ListeFidele.jrxml");
            String query = "select matricule,nom,prenoms,sexe,fonction,profession,contact,quartier from fidele";
            JRDesignQuery updateQuery = new JRDesignQuery();
            updateQuery.setText(query);
            jdesign.setQuery(updateQuery);

            JasperReport jreport = JasperCompileManager.compileReport(jdesign);
            JasperPrint jprint = JasperFillManager.fillReport(jreport,null, conn);

            JasperViewer.viewReport(jprint);

        } catch (JRException ex) {
            Logger.getLogger(Beneficiaire.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_imprimfideledimeActionPerformed

    private void matrechKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_matrechKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            DefaultTableModel model = (DefaultTableModel) tablebeneficiaire.getModel();
                 model.setRowCount(0); // vider le tableau
                try{
                        st= (Statement) conn.createStatement();
                        String req="select * from fidele where matricule='"+matrech.getText()+"'";
                        rs=st.executeQuery(req);
            //          while(rs.next()){
                           if (rs.next()) {
                             Object [] fide={rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),
                             rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10),rs.getString(11)};
                                  model.addRow(fide);
                              }else{
                                JOptionPane.showMessageDialog(null, "Vérifier votre saisie !");
                            }
                          tablebeneficiaire.setModel(model);
                           matrech.setText("");
                        }
                    catch(SQLException se){
                            JOptionPane.showMessageDialog(this, se.getMessage());
                }
        }
        
    }//GEN-LAST:event_matrechKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Beneficiaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Beneficiaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Beneficiaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Beneficiaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Beneficiaire().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accueil;
    private javax.swing.JButton actualiser;
    private javax.swing.JButton afficherbenef;
    private javax.swing.JButton ajouterbenf;
    private javax.swing.JComboBox<String> comboparent;
    private javax.swing.JComboBox combosexe;
    private javax.swing.JTextField contactbenf;
    private com.toedter.calendar.JDateChooser datenaiss;
    private javax.swing.JButton imprimfideledime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField mat;
    private javax.swing.JTextField matrech;
    private javax.swing.JButton modif;
    private javax.swing.JTextField nombenf;
    private javax.swing.JTextField prenombenf;
    private javax.swing.JTextField professionbenf;
    private javax.swing.JTextField quartierbenf;
    private javax.swing.JButton searchMembre;
    private javax.swing.JTable tablebeneficiaire;
    // End of variables declaration//GEN-END:variables
}
