/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetfime;;


import net.proteanit.sql.DbUtils;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author hp
 */
public class EnregistrerContribution extends javax.swing.JFrame {

    Connection conn;
    PreparedStatement ps;
    Statement st;
    ResultSet rs;
    static String test;
    public static String tt3;
   
            

    /**
     * Creates new form Fimeco
     */
     
    public EnregistrerContribution() {
        
        initComponents();

        //modifier le titre du formulaire
        this.setTitle("Enregistrement de Fimeco");
        //centrer le formulaire
        this.setLocationRelativeTo(null);
        //ne pas permettre le redimensionnement du formulaire
        this.setResizable(false);
        this.setIconImage(new ImageIcon(getClass().getResource("pentecote.png")).getImage());
        conn = ConexionBD.Conexion();
    }
  
    
    
    public void afficherEnregistreFimeco(){
      
        try {
            String requete = "select dateVersement,montantVerse,numFimeco,numMembre from enregistrerfimeco";
            ps = conn.prepareStatement(requete);
            rs = ps.executeQuery();
            tabenregistrerFimeco.setModel(DbUtils.resultSetToTableModel(rs));
          }  catch (Exception e) {
           JOptionPane.showMessageDialog(null, "erreur BD");
        }
     }
     
    
    public void clear() {
        nummembre.setText("");
        nummembre.setText("");
        dateverse.setDate(null);
        montverse.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        enregistrer = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        enregistrerdime = new javax.swing.JButton();
        modifier = new javax.swing.JButton();
        afficherEnregistrerFimeco = new javax.swing.JButton();
        actualiser = new javax.swing.JButton();
        accueil = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        nummembre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        montverse = new javax.swing.JTextField();
        dateverse = new com.toedter.calendar.JDateChooser();
        cdefimeco = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabenregistrerFimeco = new javax.swing.JTable();
        rechercherparCodeFime = new javax.swing.JButton();
        rechtable = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        enregistrer.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        enregistrer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Button-Add-icon.png"))); // NOI18N
        enregistrer.setText("Enregistrer");
        enregistrer.setPreferredSize(new java.awt.Dimension(99, 31));
        enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregistrerActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel13.setText("Enregistrement de fimeco");

        enregistrerdime.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        enregistrerdime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/file (2).png"))); // NOI18N
        enregistrerdime.setText("Rapports");
        enregistrerdime.setMaximumSize(new java.awt.Dimension(99, 31));
        enregistrerdime.setMinimumSize(new java.awt.Dimension(99, 31));
        enregistrerdime.setPreferredSize(new java.awt.Dimension(99, 31));
        enregistrerdime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregistrerdimeActionPerformed(evt);
            }
        });

        modifier.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        modifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update icon.png"))); // NOI18N
        modifier.setText("Modifier");
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });

        afficherEnregistrerFimeco.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        afficherEnregistrerFimeco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icone affichage1.jpg"))); // NOI18N
        afficherEnregistrerFimeco.setText("Afficher");
        afficherEnregistrerFimeco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afficherEnregistrerFimecoActionPerformed(evt);
            }
        });

        actualiser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/actualiser.jpg"))); // NOI18N
        actualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualiserActionPerformed(evt);
            }
        });

        accueil.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        accueil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/accueil1.png"))); // NOI18N
        accueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accueilActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 0, 255), new java.awt.Color(51, 0, 255)));
        jPanel1.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Montant versé");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Code Fimeco");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("Date versement");

        nummembre.setBackground(new java.awt.Color(204, 255, 204));
        nummembre.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Nom membre");

        montverse.setBackground(new java.awt.Color(204, 255, 204));
        montverse.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        dateverse.setBackground(new java.awt.Color(204, 255, 204));
        dateverse.setForeground(new java.awt.Color(204, 255, 204));
        dateverse.setDateFormatString("yyyy-MM-dd");
        dateverse.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        dateverse.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                dateverseComponentAdded(evt);
            }
        });
        dateverse.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                dateverseAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        dateverse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                dateverseMouseReleased(evt);
            }
        });
        dateverse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dateverseKeyReleased(evt);
            }
        });

        cdefimeco.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(43, 45, Short.MAX_VALUE)
                                .addComponent(nummembre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dateverse, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(montverse, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(cdefimeco))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(dateverse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(montverse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdefimeco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nummembre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tabenregistrerFimeco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date versement", "Montant versé", "Code Fimeco", "Membre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabenregistrerFimeco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabenregistrerFimecoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabenregistrerFimeco);

        rechercherparCodeFime.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rechercherparCodeFime.setText("Rechercher par code fimeco");
        rechercherparCodeFime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercherparCodeFimeActionPerformed(evt);
            }
        });

        rechtable.setBackground(new java.awt.Color(204, 255, 204));
        rechtable.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rechtable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rechtableKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(actualiser, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(accueil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(263, 263, 263)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(afficherEnregistrerFimeco, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(rechercherparCodeFime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(rechtable, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(enregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                                .addComponent(modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88)
                                .addComponent(enregistrerdime, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))))
                .addGap(9, 9, 9))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(actualiser, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accueil, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(afficherEnregistrerFimeco, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rechercherparCodeFime, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rechtable, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(enregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enregistrerdime, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enregistrerdimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrerdimeActionPerformed
        RapportContributionMembre rapp = new RapportContributionMembre();
        rapp.setVisible(true);
//                       this.dispose();
    }//GEN-LAST:event_enregistrerdimeActionPerformed

    private void enregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrerActionPerformed

        String requet = "insert into dime (codeDime,numeroFidele,dateVersement,montantHebdo) values(?,?,?,?)";
        try {
            ps = conn.prepareStatement(requet);

            ps.setString(1, nummembre.getText());
            ps.setInt(2, Integer.parseInt(nummembre.getText()));
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(dateverse.getDate());
            ps.setString(3, date);
            ps.setString(4, montverse.getText());
            ps.executeUpdate();
            //   JOptionPane.showMessageDialog(this,"Insertion réussie!!!");
            nummembre.setText("");
            nummembre.setText("");
            dateverse.setDate(null);
            montverse.setText("");
            afficherEnregistreFimeco();
        } catch (SQLException ex) {
            Logger.getLogger(Beneficiaire.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_enregistrerActionPerformed

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
        
        DefaultTableModel d1 = (DefaultTableModel)tabenregistrerFimeco.getModel();
        int selectIndex = tabenregistrerFimeco.getSelectedRow();

        int numeroDime = Integer.parseInt(d1.getValueAt(selectIndex, 0).toString());
        String codeDime = nummembre.getText();
        int numeroFidele = Integer.parseInt(nummembre.getText());
        String montantHebdo = montverse.getText();
        String dateVersement = ((JTextField) dateverse.getDateEditor().getUiComponent()).getText();

        try {
            ps = conn.prepareStatement("update dime set codeDime=?,numeroFidele=?,montantHebdo=?,"
                                     + "dateVersement=? where numeroDime= ?");     
            ps.setString(1, codeDime);
            ps.setInt(2, numeroFidele);
            ps.setString(3, montantHebdo);
            ps.setString(4, dateVersement);
            ps.setInt(5, numeroDime);
            ps.executeUpdate();
//            JOptionPane.showMessageDialog(null,"Mise à jour effectuée!");
            afficherEnregistreFimeco();
            
            nummembre.setText("");
            nummembre.setText("");
            dateverse.setDate(null);
            montverse.setText("");
          
            nummembre.requestFocus();
        } 
        catch (SQLException ex) {
            Logger.getLogger(EnregistrerContribution.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_modifierActionPerformed

    private void dateverseComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_dateverseComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_dateverseComponentAdded

    private void dateverseAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_dateverseAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_dateverseAncestorAdded

    private void dateverseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateverseMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_dateverseMouseReleased

    private void dateverseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateverseKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_dateverseKeyReleased

    private void afficherEnregistrerFimecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afficherEnregistrerFimecoActionPerformed
        afficherEnregistreFimeco();
    }//GEN-LAST:event_afficherEnregistrerFimecoActionPerformed

    private void actualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualiserActionPerformed
        // TODO add your handling code here:
        EnregistrerContribution edm = new EnregistrerContribution();
        edm.setVisible(true);
        dispose();
    }//GEN-LAST:event_actualiserActionPerformed

    private void accueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accueilActionPerformed
        // TODO add your handling code here:
        Accueil acc = new Accueil();
        acc.setVisible(true);
        dispose();
    }//GEN-LAST:event_accueilActionPerformed

    private void tabenregistrerFimecoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabenregistrerFimecoMouseClicked

        try {
 
            int i = tabenregistrerFimeco.getSelectedRow();
            TableModel model = tabenregistrerFimeco.getModel();
            
            String datet = tabenregistrerFimeco.getModel().getValueAt(i, 1).toString();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date date = sdf.parse(datet);
            dateverse.setDate(date);
            montverse.setText(model.getValueAt(i,2).toString()); 
            cdefimeco.setText(model.getValueAt(i,3).toString());
            nummembre.setText(model.getValueAt(i,4).toString());
            
        } catch (ParseException ex) {
            Logger.getLogger(EnregistrerContribution.class.getName()).log(Level.SEVERE, null, ex);
        }
           
    }//GEN-LAST:event_tabenregistrerFimecoMouseClicked

    private void rechercherparCodeFimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercherparCodeFimeActionPerformed
        // TODO add your handling code here:
                DefaultTableModel model = (DefaultTableModel) tabenregistrerFimeco.getModel();
                 model.setRowCount(0); // vider le tableau
                try{
                        st= (Statement) conn.createStatement();
                        String req="select * from fimeco where codeDime='"+rechtable.getText()+"'";
                        rs=st.executeQuery(req);
            //          while(rs.next()){
                           if (rs.next()) {
                                  Object [] mem={rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)};
                                  model.addRow(mem);
                              }else{
                                JOptionPane.showMessageDialog(null, "Vérifier votre saisie !");
                            }
                          tabenregistrerFimeco.setModel(model);
                          rechtable.setText("");
                        }
                    catch(SQLException se){
                            JOptionPane.showMessageDialog(this, se.getMessage());
                        }

    }//GEN-LAST:event_rechercherparCodeFimeActionPerformed

    private void rechtableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rechtableKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            DefaultTableModel model = (DefaultTableModel) tabenregistrerFimeco.getModel();
                 model.setRowCount(0); // vider le tableau
                try{
                        st= (Statement) conn.createStatement();
                        String req="select * from dime where codeDime='"+rechtable.getText()+"'";
                        rs=st.executeQuery(req);
            //          while(rs.next()){
                           if (rs.next()) {
                                  Object [] mem={rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)};
                                  model.addRow(mem);
                              }else{
                                JOptionPane.showMessageDialog(null, "Vérifier votre saisie !");
                            }
                          tabenregistrerFimeco.setModel(model);
                          rechtable.setText("");
                        }
                    catch(SQLException se){
                            JOptionPane.showMessageDialog(this, se.getMessage());
                        }
           }
    }//GEN-LAST:event_rechtableKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnregistrerContribution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnregistrerContribution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnregistrerContribution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnregistrerContribution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnregistrerContribution().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accueil;
    private javax.swing.JButton actualiser;
    private javax.swing.JButton afficherEnregistrerFimeco;
    private javax.swing.JTextField cdefimeco;
    private com.toedter.calendar.JDateChooser dateverse;
    private javax.swing.JButton enregistrer;
    private javax.swing.JButton enregistrerdime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modifier;
    private javax.swing.JTextField montverse;
    private javax.swing.JTextField nummembre;
    private javax.swing.JButton rechercherparCodeFime;
    private javax.swing.JTextField rechtable;
    private javax.swing.JTable tabenregistrerFimeco;
    // End of variables declaration//GEN-END:variables
}
