/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetfime;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 */
public class MontantContributionPeriodique extends javax.swing.JFrame {
Connection conn;
PreparedStatement ps;
Statement st;
ResultSet rs;
DefaultTableModel dtm;
    /**
     * Creates new form Fidele
     */
    public MontantContributionPeriodique() {
        initComponents();
        
        //modifier le titre du formulaire
        this.setTitle("Rapport de prime");
        //centrer le formulaire
        this.setLocationRelativeTo(null);
        //ne pas permettre le redimensionnement du formulaire
        this.setResizable(false);
        
        this.setIconImage(new ImageIcon(getClass().getResource("pentecote.png")).getImage());
        conn = ConexionBD.Conexion();
    }


    public void cleardata() {
                datedime1.setDate(null);
                datedime2.setDate(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rechercherpardatetotaldime = new javax.swing.JButton();
        datedime1 = new com.toedter.calendar.JDateChooser();
        datedime2 = new com.toedter.calendar.JDateChooser();
        impression = new javax.swing.JButton();
        texteaff = new java.awt.Label();
        accueil = new javax.swing.JButton();
        gererFimeco = new javax.swing.JButton();
        gererMembre = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel9.setText("de");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Montant total de Fimeco pendant une période");

        rechercherpardatetotaldime.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rechercherpardatetotaldime.setText("Rechercher par date");
        rechercherpardatetotaldime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercherpardatetotaldimeActionPerformed(evt);
            }
        });

        datedime1.setBackground(new java.awt.Color(204, 255, 204));
        datedime1.setForeground(new java.awt.Color(204, 255, 204));
        datedime1.setDateFormatString("yyyy-MM-dd\n");
        datedime1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        datedime1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                datedime1ComponentAdded(evt);
            }
        });
        datedime1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                datedime1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        datedime1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                datedime1MouseReleased(evt);
            }
        });
        datedime1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                datedime1KeyReleased(evt);
            }
        });

        datedime2.setBackground(new java.awt.Color(204, 255, 204));
        datedime2.setForeground(new java.awt.Color(204, 255, 204));
        datedime2.setDateFormatString("yyyy-MM-dd\n");
        datedime2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        datedime2.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                datedime2ComponentAdded(evt);
            }
        });
        datedime2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                datedime2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        datedime2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                datedime2MouseReleased(evt);
            }
        });
        datedime2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                datedime2KeyReleased(evt);
            }
        });

        impression.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        impression.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/printer.png"))); // NOI18N
        impression.setText("Imprimer");
        impression.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                impressionActionPerformed(evt);
            }
        });

        texteaff.setBackground(new java.awt.Color(255, 255, 255));
        texteaff.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        accueil.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        accueil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/accueil1.png"))); // NOI18N
        accueil.setText("Accueil");
        accueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accueilActionPerformed(evt);
            }
        });

        gererFimeco.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        gererFimeco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/argent1nv.png"))); // NOI18N
        gererFimeco.setText("Gérer fimeco");
        gererFimeco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gererFimecoActionPerformed(evt);
            }
        });

        gererMembre.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        gererMembre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fidel.png"))); // NOI18N
        gererMembre.setText("Gérer membres");
        gererMembre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gererMembreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(accueil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gererFimeco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gererMembre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(impression, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(rechercherpardatetotaldime, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(datedime1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel9)
                                .addGap(30, 30, 30)
                                .addComponent(datedime2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(202, 202, 202)
                                .addComponent(texteaff, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(16, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(115, 115, 115))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rechercherpardatetotaldime)
                            .addComponent(gererFimeco)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(accueil)
                                    .addComponent(jLabel1))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(datedime2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(7, 7, 7))
                                    .addComponent(datedime1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(gererMembre)
                        .addGap(23, 23, 23)
                        .addComponent(impression, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(texteaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(178, 178, 178))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
  
    }//GEN-LAST:event_formWindowOpened

    private void rechercherpardatetotaldimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercherpardatetotaldimeActionPerformed
        
        String dateversement1 =((JTextField)datedime1.getDateEditor().getUiComponent()).getText();
        String dateversement2 =((JTextField)datedime2.getDateEditor().getUiComponent()).getText();
        
        String req5 ="select sum(montantHebdo) from dime "
                + "where dateVersement between '"+ dateversement1+"' and '"+ dateversement2+"'";
        try{  
            ps = conn.prepareStatement(req5);
            rs = ps.executeQuery();
            while(rs.next()){
            texteaff.setText(rs.getString(1));
             }        
        } catch (SQLException ex){
          JOptionPane.showMessageDialog(this, "Problème de connexion avec la base de données");
        }          
    }//GEN-LAST:event_rechercherpardatetotaldimeActionPerformed

    private void datedime1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_datedime1ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_datedime1ComponentAdded

    private void datedime1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_datedime1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_datedime1AncestorAdded

    private void datedime1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datedime1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_datedime1MouseReleased

    private void datedime1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_datedime1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_datedime1KeyReleased

    private void datedime2ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_datedime2ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_datedime2ComponentAdded

    private void datedime2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_datedime2AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_datedime2AncestorAdded

    private void datedime2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datedime2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_datedime2MouseReleased

    private void datedime2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_datedime2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_datedime2KeyReleased

    private void impressionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_impressionActionPerformed
        // TODO add your handling code here:
        String date1 =((JTextField)datedime1.getDateEditor().getUiComponent()).getText();
        String date2 =((JTextField)datedime2.getDateEditor().getUiComponent()).getText();
        Map parameters = new HashMap();
	parameters.put("date1", date1);
	parameters.put("date2", date2); 
        try {    
        JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\Kluce\\Documents\\NetBeansProjects\\Fimeco\\src\\report\\Montantprime.jrxml");
            JasperReport jreport = JasperCompileManager.compileReport(jdesign);
            JasperPrint jprint = JasperFillManager.fillReport(jreport, parameters, conn);
            JasperViewer jv = new JasperViewer(jprint, false);
            jv.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            jv.setVisible(true);
        } catch (JRException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }           
    }//GEN-LAST:event_impressionActionPerformed

    private void accueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accueilActionPerformed
        // TODO add your handling code here:
        Accueil acc = new Accueil();
        acc.setVisible(true);
    }//GEN-LAST:event_accueilActionPerformed

    private void gererFimecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gererFimecoActionPerformed
        // TODO add your handling code here:
        EnregistrerContribution gestprm = new EnregistrerContribution();
        gestprm.setVisible(true);
    }//GEN-LAST:event_gererFimecoActionPerformed

    private void gererMembreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gererMembreActionPerformed
        // TODO add your handling code here:
        Beneficiaire gestmr = new Beneficiaire();
        gestmr.setVisible(true);
    }//GEN-LAST:event_gererMembreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MontantContributionPeriodique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MontantContributionPeriodique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MontantContributionPeriodique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MontantContributionPeriodique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MontantContributionPeriodique().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accueil;
    private com.toedter.calendar.JDateChooser datedime1;
    private com.toedter.calendar.JDateChooser datedime2;
    private javax.swing.JButton gererFimeco;
    private javax.swing.JButton gererMembre;
    private javax.swing.JButton impression;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton rechercherpardatetotaldime;
    private java.awt.Label texteaff;
    // End of variables declaration//GEN-END:variables
}
