/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetfime;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author hp
 */
public class RapportContributionMembre extends javax.swing.JFrame {
Connection conn;
PreparedStatement ps;
Statement st;
ResultSet rs;
DefaultTableModel dtm;
    /**
     * Creates new form Fidele
     */
    public RapportContributionMembre() {
        initComponents();
        
        //modifier le titre du formulaire
        this.setTitle("Rapport des dîmes par fidèles");
        //centrer le formulaire
        this.setLocationRelativeTo(null);
        //ne pas permettre le redimensionnement du formulaire
        this.setResizable(false);
        
        dtm = new DefaultTableModel();
        dtm.addColumn("Nom");
        dtm.addColumn("Prénoms");
        dtm.addColumn("Contact");
        dtm.addColumn("Date");
        dtm.addColumn("Montant versé");
        tabledimesfideles.setModel(dtm);    
 
        this.setIconImage(new ImageIcon(getClass().getResource("pentecote.png")).getImage());
        conn = ConexionBD.Conexion();
    }

    public void cleardata() {
                datea.setDate(null);
                dateb.setDate(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rechercherpar = new javax.swing.JButton();
        datea = new com.toedter.calendar.JDateChooser();
        dateb = new com.toedter.calendar.JDateChooser();
        membre = new javax.swing.JButton();
        initialiser = new javax.swing.JButton();
        prime = new javax.swing.JButton();
        fimecoIndividuelle = new javax.swing.JButton();
        montantFimecoPeriodique = new javax.swing.JButton();
        impressionrap = new javax.swing.JButton();
        accueil = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabledimesfideles = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel9.setText("de");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Montant total de contribution par membre pendant une période");

        rechercherpar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rechercherpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        rechercherpar.setText("Rechercher par date");
        rechercherpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercherparActionPerformed(evt);
            }
        });

        datea.setBackground(new java.awt.Color(204, 255, 204));
        datea.setForeground(new java.awt.Color(204, 255, 204));
        datea.setDateFormatString("yyyy-MM-dd\n");
        datea.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        datea.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                dateaComponentAdded(evt);
            }
        });
        datea.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                dateaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        datea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                dateaMouseReleased(evt);
            }
        });
        datea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dateaKeyReleased(evt);
            }
        });

        dateb.setBackground(new java.awt.Color(204, 255, 204));
        dateb.setForeground(new java.awt.Color(204, 255, 204));
        dateb.setDateFormatString("yyyy-MM-dd\n");
        dateb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        dateb.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                datebComponentAdded(evt);
            }
        });
        dateb.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                datebAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        dateb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                datebMouseReleased(evt);
            }
        });
        dateb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                datebKeyReleased(evt);
            }
        });

        membre.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        membre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fidel.png"))); // NOI18N
        membre.setText("Membres");
        membre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                membreActionPerformed(evt);
            }
        });

        initialiser.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        initialiser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Button-Refresh-icon (1).png"))); // NOI18N
        initialiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initialiserActionPerformed(evt);
            }
        });

        prime.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        prime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/argent1nv.png"))); // NOI18N
        prime.setText("Contribution");
        prime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeActionPerformed(evt);
            }
        });

        fimecoIndividuelle.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        fimecoIndividuelle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/argent1nv.png"))); // NOI18N
        fimecoIndividuelle.setText("Contribution individuelle");
        fimecoIndividuelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fimecoIndividuelleActionPerformed(evt);
            }
        });

        montantFimecoPeriodique.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        montantFimecoPeriodique.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/argent1nv.png"))); // NOI18N
        montantFimecoPeriodique.setText("Montant contribution par période");
        montantFimecoPeriodique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montantFimecoPeriodiqueActionPerformed(evt);
            }
        });

        impressionrap.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        impressionrap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/printer.png"))); // NOI18N
        impressionrap.setText("Imprimer rapport");
        impressionrap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                impressionrapActionPerformed(evt);
            }
        });

        accueil.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        accueil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/accueil1.png"))); // NOI18N
        accueil.setText("Accueil");
        accueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accueilActionPerformed(evt);
            }
        });

        tabledimesfideles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabledimesfideles);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(membre, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accueil, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(prime, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(initialiser)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(319, 319, 319))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rechercherpar, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(datea, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel9)
                        .addGap(46, 46, 46)
                        .addComponent(dateb, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1005, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 10, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(montantFimecoPeriodique)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fimecoIndividuelle)
                .addGap(124, 124, 124)
                .addComponent(impressionrap, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(accueil))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(prime)
                        .addComponent(initialiser, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rechercherpar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(datea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)))
                .addGap(10, 10, 10)
                .addComponent(membre)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fimecoIndividuelle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(montantFimecoPeriodique, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(impressionrap, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
  
    }//GEN-LAST:event_formWindowOpened

    private void rechercherparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercherparActionPerformed
        // Le code est ce qui suit   select fidele.numeroFidele as 'Matricule',codeDime as 'Code dîme',nom as 'Nom',"
        String dateversement1 =((JTextField)datea.getDateEditor().getUiComponent()).getText();
        String dateversement2 =((JTextField)dateb.getDateEditor().getUiComponent()).getText();
        
        String req5 ="select matricule as 'Matricule',codeDime as 'Code dîme',nom as 'Nom',"
                + "prenoms as 'Prénoms',contact as 'Contact',fonction as 'Fonction',sum(montantHebdo) as 'Total' "
                + "from fidele inner join dime "
                + "on fidele.numeroFidele = dime.numeroFidele "
                + "where dateVersement between '"+ dateversement1+"' and '"+ dateversement2+"' "
                + "group by matricule";
        try{  
            ps = conn.prepareStatement(req5);
            rs = ps.executeQuery();
            tabledimesfideles.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex){
          JOptionPane.showMessageDialog(this, "Problème de connexion avec la base de données");
        }
    }//GEN-LAST:event_rechercherparActionPerformed

    private void dateaComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_dateaComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_dateaComponentAdded

    private void dateaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_dateaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_dateaAncestorAdded

    private void dateaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateaMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_dateaMouseReleased

    private void dateaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_dateaKeyReleased

    private void datebComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_datebComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_datebComponentAdded

    private void datebAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_datebAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_datebAncestorAdded

    private void datebMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datebMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_datebMouseReleased

    private void datebKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_datebKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_datebKeyReleased

    private void membreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_membreActionPerformed
        // TODO add your handling code here:
        
        Beneficiaire mbr = new Beneficiaire();
                        mbr.setVisible(true);
    }//GEN-LAST:event_membreActionPerformed

    private void initialiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initialiserActionPerformed
        // TODO add your handling code here:
        datea.setDate(null);
        dateb.setDate(null);
    }//GEN-LAST:event_initialiserActionPerformed

    private void primeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeActionPerformed
        // TODO add your handling code here:
        
        EnregistrerContribution prm = new EnregistrerContribution();
              prm.setVisible(true);
    }//GEN-LAST:event_primeActionPerformed

    private void fimecoIndividuelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fimecoIndividuelleActionPerformed
        // TODO add your handling code here:
        
        ContributionIndividuelle fimecoind = new ContributionIndividuelle();
                         fimecoind.setVisible(true);
    }//GEN-LAST:event_fimecoIndividuelleActionPerformed

    private void montantFimecoPeriodiqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montantFimecoPeriodiqueActionPerformed
        // TODO add your handling code here:
        
        MontantContributionPeriodique mtdimp = new MontantContributionPeriodique();
                           mtdimp.setVisible(true);
    }//GEN-LAST:event_montantFimecoPeriodiqueActionPerformed

    private void impressionrapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_impressionrapActionPerformed

        String debutdate =((JTextField)datea.getDateEditor().getUiComponent()).getText();
        String findate =((JTextField)dateb.getDateEditor().getUiComponent()).getText();
        
       
        Map parameters = new HashMap();
	parameters.put("debutdate", debutdate);
	parameters.put("findate", findate);

        try {
       
        JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\Kluce\\Documents\\NetBeansProjects\\Fimeco\\src\\report\\rapportmensuel.jrxml");
            JasperReport jreport = JasperCompileManager.compileReport(jdesign);

            JasperPrint jprint = JasperFillManager.fillReport(jreport, parameters, conn);
            JasperViewer jv = new JasperViewer(jprint, false);
            jv.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            jv.setVisible(true);
  
        } catch (JRException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_impressionrapActionPerformed

    private void accueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accueilActionPerformed
        // TODO add your handling code here:
        Accueil acc = new Accueil();  
        acc.setVisible(true);
    }//GEN-LAST:event_accueilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RapportContributionMembre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RapportContributionMembre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RapportContributionMembre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RapportContributionMembre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RapportContributionMembre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accueil;
    private com.toedter.calendar.JDateChooser datea;
    private com.toedter.calendar.JDateChooser dateb;
    private javax.swing.JButton fimecoIndividuelle;
    private javax.swing.JButton impressionrap;
    private javax.swing.JButton initialiser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton membre;
    private javax.swing.JButton montantFimecoPeriodique;
    private javax.swing.JButton prime;
    private javax.swing.JButton rechercherpar;
    private javax.swing.JTable tabledimesfideles;
    // End of variables declaration//GEN-END:variables
}
