/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetfime;;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 */
public class Utilisateur extends javax.swing.JFrame {
Connection conn;
PreparedStatement ps;
Statement st;
ResultSet rs;
static String test;


    /**
     * Creates new form Fidele
     */
    public Utilisateur() {
        initComponents();
//        conx = PConnexion.pconnexion();
        
        //modifier le titre du formulaire
        this.setTitle("Fidele");
        //centrer le formulaire
        this.setLocationRelativeTo(null);
        //ne pas permettre le redimensionnement du formulaire
        this.setResizable(false);
        conn = ConexionBD.Conexion();
    }
    
    public void cleardata() {
        
        txtmotpasse.setText("");
        txtcompte.setText("");
        comboqualite.setSelectedIndex(-1);
        txtnom.setText("");
        txtprenom.setText("");
    }
    
    public void afficherutilisateur(){
        
    }
    
    public void Deplace() {
        try {

            int row = tabutilisateur.getSelectedRow();
            this.test = (tabutilisateur.getModel().getValueAt(row, 0).toString());
            String req = " select * from  utilisateur where nom = '" + test + "'  ";
            ps = conn.prepareStatement(req);
            rs = ps.executeQuery();

            if (rs.next()) {
                String t1 = rs.getString("motpasse");
                txtmotpasse.setText(t1);
                String t2 = rs.getString("compte");
                txtcompte.setText(t2);
                String t3 = rs.getString("qualite");
                comboqualite.addItem(t3);
                
                String t4 = rs.getString("nom");
                txtnom.setText(t4);
                String t5 = rs.getString("prenoms");
                txtprenom.setText(t5);
            }
 
        } catch (Exception e) {
            System.out.println(e);
            
       }
        
     }
    
    public String gettableresult() {
        return test;
    }
    
    public void Affichage() {
        try {
            String requete = "select motpasse as 'Mot de passe' ,compte as 'Compte' ,qualite as 'Qualité' ,nom as 'Nom',prenoms as 'Prenoms' from utilisateur";
            ps = conn.prepareStatement(requete);
            rs = ps.executeQuery();
            tabutilisateur.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            System.out.println(e);
        }
//        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnajout = new javax.swing.JButton();
        txtcompte = new javax.swing.JTextField();
        txtmotpasse = new javax.swing.JTextField();
        btnmodif = new javax.swing.JButton();
        rechbtnFidele = new javax.swing.JButton();
        rechval = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        allerfimeco = new javax.swing.JButton();
        comboqualite = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabutilisateur = new javax.swing.JTable();
        actualiser1 = new javax.swing.JButton();
        txtnom = new javax.swing.JTextField();
        txtprenom = new javax.swing.JTextField();
        afficherutilisateur = new javax.swing.JButton();
        accueil = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel3.setText("Nom");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel5.setText("Prénoms");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel9.setText("Compte");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel11.setText("Mot de passe");

        btnajout.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnajout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Button-Add-icon.png"))); // NOI18N
        btnajout.setText("Ajouter");
        btnajout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnajout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajoutActionPerformed(evt);
            }
        });

        txtcompte.setBackground(new java.awt.Color(204, 255, 204));
        txtcompte.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtcompte.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtmotpasse.setBackground(new java.awt.Color(204, 255, 204));
        txtmotpasse.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtmotpasse.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnmodif.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnmodif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update icon.png"))); // NOI18N
        btnmodif.setText("Modifier");
        btnmodif.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnmodif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifActionPerformed(evt);
            }
        });

        rechbtnFidele.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rechbtnFidele.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        rechbtnFidele.setText("Recherche");
        rechbtnFidele.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rechbtnFidele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechbtnFideleActionPerformed(evt);
            }
        });

        rechval.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rechval.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        rechval.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rechvalKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel8.setText("Type");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Gérer les utilisateurs");

        allerfimeco.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        allerfimeco.setForeground(java.awt.Color.blue);
        allerfimeco.setText("Aller à la page administration");
        allerfimeco.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        allerfimeco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allerfimecoActionPerformed(evt);
            }
        });

        comboqualite.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        comboqualite.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Responsable", "Officier", "Fidele" }));
        comboqualite.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        tabutilisateur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identifiant", "Mot de passe", "Compte", "Qualite", "Nom", "Prenoms"
            }
        ));
        jScrollPane1.setViewportView(tabutilisateur);

        actualiser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/actualiser.jpg"))); // NOI18N
        actualiser1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        actualiser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualiser1ActionPerformed(evt);
            }
        });

        txtnom.setBackground(new java.awt.Color(204, 255, 204));
        txtnom.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtnom.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtprenom.setBackground(new java.awt.Color(204, 255, 204));
        txtprenom.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtprenom.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        afficherutilisateur.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        afficherutilisateur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icone affichage1.jpg"))); // NOI18N
        afficherutilisateur.setText("Afficher");
        afficherutilisateur.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        afficherutilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afficherutilisateurActionPerformed(evt);
            }
        });

        accueil.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        accueil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/accueil1.png"))); // NOI18N
        accueil.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        accueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accueilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(rechbtnFidele, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(rechval))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnajout, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnmodif, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtmotpasse, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtcompte, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(88, 88, 88)
                                                .addComponent(comboqualite, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel5))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(1, 1, 1))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnom, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(txtprenom))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(allerfimeco, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                        .addGap(3, 3, 3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(afficherutilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(actualiser1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(accueil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(278, 278, 278))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(accueil, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(actualiser1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmotpasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcompte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(comboqualite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtprenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnajout)
                    .addComponent(btnmodif)
                    .addComponent(afficherutilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(allerfimeco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rechbtnFidele, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rechval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
  
    }//GEN-LAST:event_formWindowOpened

    private void btnajoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajoutActionPerformed

        String req="insert into utilisateur (motpasse,compte,qualite,nom,prenoms) values(?,?,?,?,?)";
        try{
            ps = conn.prepareStatement(req);
            ps.setString(1, txtmotpasse.getText());
            ps.setString(2, txtcompte.getText());
            ps.setString(3, (String) comboqualite.getSelectedItem());
            ps.setString(4, txtnom.getText());
            ps.setString(5, txtprenom.getText());
            ps.executeUpdate();
            // JOptionPane.showMessageDialog(this,"Insertion réussie!!!");
            txtmotpasse.setText("");
            txtcompte.setText("");
            comboqualite.setSelectedIndex(-1);
            txtnom.setText("");
            txtprenom.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(Utilisateur.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnajoutActionPerformed

    private void btnmodifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifActionPerformed
        // TODO add your handling code here:   motpasse,compte,qualite,nom,prenoms
        DefaultTableModel d1 = (DefaultTableModel)tabutilisateur.getModel();
        int selectIndex = tabutilisateur.getSelectedRow();

        int utilid = Integer.parseInt(d1.getValueAt(selectIndex, 0).toString());
        String compte = txtcompte.getText();
        String motpasse  = txtmotpasse.getText();
        String qualite = (String) comboqualite.getSelectedItem();
        String nom = txtnom.getText();
        String prenoms = txtprenom.getText();
        try {    
        ps = conn.prepareStatement("update fidele set compte=?,motpasse=?,qualite=?,nom=?,prenoms=? where utilid=?");
        ps.setString(1, compte);
        ps.setString(2, motpasse);
        ps.setString(3, qualite);
        ps.setString(4, nom);
        ps.setString(5, prenoms);
        ps.setInt(6, utilid);  
        ps.executeUpdate();
//      JOptionPane.showMessageDialog(null,"Mise à jour effectuée!");
            afficherutilisateur();
            
            txtmotpasse.setText("");
            txtcompte.setText("");
            comboqualite.setSelectedIndex(-1);
            txtnom.setText("");
            txtprenom.setText("");
          
            txtmotpasse.requestFocus();
        } 
        catch (SQLException ex) {
            Logger.getLogger(Beneficiaire.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnmodifActionPerformed

    private void rechbtnFideleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechbtnFideleActionPerformed
        
        DefaultTableModel model = (DefaultTableModel) tabutilisateur.getModel();
                 model.setRowCount(0); // vider le tableau
                try{
                        st= (Statement) conn.createStatement();
                        String req="select * from fidele where nom='"+rechval.getText()+"'";
                        rs=st.executeQuery(req);
            //          while(rs.next()){
                           if (rs.next()) {
                             Object [] fide={rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)};
                                  model.addRow(fide);
                              }else{
                                JOptionPane.showMessageDialog(null, "Vérifier votre saisie !");
                            }
                          tabutilisateur.setModel(model);
                           rechval.setText("");
                        }
                    catch(SQLException se){
                            JOptionPane.showMessageDialog(this, se.getMessage());
                        }
        
    }//GEN-LAST:event_rechbtnFideleActionPerformed

    private void allerfimecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allerfimecoActionPerformed

                Administration admin = new Administration();
                admin.setVisible(true);
    }//GEN-LAST:event_allerfimecoActionPerformed

    private void actualiser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualiser1ActionPerformed
        // TODO add your handling code here:
        Utilisateur util = new Utilisateur();
        util.setVisible(true);
        dispose();
    }//GEN-LAST:event_actualiser1ActionPerformed

    private void accueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accueilActionPerformed
        // TODO add your handling code here:
        Accueil acc = new Accueil();
        acc.setVisible(true);
        dispose();
    }//GEN-LAST:event_accueilActionPerformed

    private void afficherutilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afficherutilisateurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_afficherutilisateurActionPerformed

    private void rechvalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rechvalKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_rechvalKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Utilisateur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accueil;
    private javax.swing.JButton actualiser1;
    private javax.swing.JButton afficherutilisateur;
    private javax.swing.JButton allerfimeco;
    private javax.swing.JButton btnajout;
    private javax.swing.JButton btnmodif;
    private javax.swing.JComboBox comboqualite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton rechbtnFidele;
    private javax.swing.JTextField rechval;
    private javax.swing.JTable tabutilisateur;
    private javax.swing.JTextField txtcompte;
    private javax.swing.JTextField txtmotpasse;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtprenom;
    // End of variables declaration//GEN-END:variables
}
